development:
  adapter: postgresql
  database: <%= ENV['DEV_DB_NAME'] %>
  username: <%= ENV['DEV_DB_USER'] %>
  password: <%= ENV['DEV_DB_PASS'] %>
  host: <%= ENV['DEV_DB_HOSTNAME'] %>
  encoding: utf8

test:
  adapter: postgresql
  database: <%= ENV['TEST_DB_NAME'] %>
  username: <%= ENV['TEST_DB_USER'] %>
  password: <%= ENV['TEST_DB_PASS'] %>
  host: <%= ENV['TEST_DB_HOSTNAME'] %>
  encoding: utf8

staging:
  adapter: postgresql
  database: <%= ENV['DB_NAME'] %>
  username: <%= ENV['DB_USER'] %>
  password: <%= ENV['DB_PASS'] %>
  host: <%= ENV['DB_HOST'] %>
  encoding: utf8

production:
  adapter: postgresql
  database: <%= ENV['DB_NAME'] %>
  username: <%= ENV['DB_USER'] %>
  password: <%= ENV['DB_PASS'] %>
  host: <%= ENV['DB_HOST'] %>
  encoding: utf8